### ISSUE TITLE
The reactor is using a hardcoded '1-SALT' registration key

### ISSUE THREAD

**Issue by dmacvicar** [SUSE/spacewalk-saltstack#1]

**Comment by PolymathMonkey** [comment]
Hi, 

I was asking myself about this issue also issue no. #2. 

What i wanted to know, is right now the hard coded admin/activation-key pair in the pillar is "pulled"
from the reactor to do the activation stuff on the spacewalk side. So the thing is you have to adjust the activation-key/username in the pillar for each spacewalk instance. And this is the thing that should get changed so it can be more dynamically? please tell if you need clarification. Thanks in advance.

Kind regards,

**Comment by dmacvicar** [comment]
Yeah, I think this was fixed already and now it is pulled from the pillar and the instructions are in the README. There is no need to do it per machine as pillars can match multiple machines.
